SELECT CONSTRAINT_NAME, SEARCH_CONDITION FROM USER_CONSTRAINTS WHERE TABLE_NAME='MEMBER' AND CONSTRAINT_TYPE='C';
-- Clean up invalid membertype rows from audit
DELETE FROM MEMBER WHERE MEMBERTYPE NOT IN ('Regular','Premium','Student') AND MEMBERNAME LIKE 'BadType%';
COMMIT;
EXIT;
