-- Fix invalid MEMBERTYPE values
UPDATE MEMBER SET MEMBERTYPE = 'Regular' WHERE MEMBERTYPE NOT IN ('Regular','Premium','Student');
COMMIT;
-- Verify fix
SELECT MEMBERTYPE, COUNT(*) FROM MEMBER GROUP BY MEMBERTYPE ORDER BY MEMBERTYPE;
EXIT;
