SET DEFINE OFF;
SET SERVEROUTPUT ON;
DECLARE
    v_cat_id NUMBER;
    v_pub_id NUMBER;
    v_branch_id NUMBER;
    v_loc_id NUMBER;
    v_book_id NUMBER;
    v_copy_id NUMBER;
    v_member_id NUMBER;
    v_lib_id NUMBER;
    v_loan_id NUMBER;
BEGIN
    FOR i IN 1..30 LOOP
        BEGIN
            INSERT INTO AUTHOR (AUTHORNAME, NATIONALITY, BIOGRAPHY) VALUES ('Author Name '||i, 'USA', 'Biography '||i);
        EXCEPTION WHEN OTHERS THEN NULL;
        END;
    END LOOP;
    
    FOR i IN 1..50 LOOP
        BEGIN
            SELECT CATEGORYID INTO v_cat_id FROM (SELECT CATEGORYID FROM CATEGORY ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1;
            SELECT PUBLISHERID INTO v_pub_id FROM (SELECT PUBLISHERID FROM PUBLISHER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1;
            INSERT INTO BOOK (TITLE, ISBN, CATEGORYID, PUBLISHERID, PRICE, EDITION, PUBLISHYEAR) 
            VALUES ('Book Title '||i, '978'||DBMS_RANDOM.VALUE(1000000000, 9999999999), v_cat_id, v_pub_id, 25.99, '1st', 2020)
            RETURNING BOOKID INTO v_book_id;
            
            INSERT INTO WRITTEN_BY (BOOKID, AUTHORID) VALUES (v_book_id, (SELECT AUTHORID FROM (SELECT AUTHORID FROM AUTHOR ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1));
        EXCEPTION WHEN OTHERS THEN NULL;
        END;
    END LOOP;
    
    FOR i IN 1..100 LOOP
        BEGIN
            INSERT INTO MEMBER (MEMBERNAME, ADDRESS, PHONE, EMAIL, MEMBERTYPE, DATEJOINED) 
            VALUES ('Member Name '||i, '123 Main St', '555-'||LPAD(i, 4, '0'), 'member'||i||'@test.com', 'Regular', SYSDATE - MOD(i, 300));
        EXCEPTION WHEN OTHERS THEN NULL;
        END;
    END LOOP;
    
    FOR i IN 1..150 LOOP
        BEGIN
            SELECT BOOKID INTO v_book_id FROM (SELECT BOOKID FROM BOOK ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1;
            SELECT BRANCHID INTO v_branch_id FROM (SELECT BRANCHID FROM LIBRARY_BRANCH ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1;
            SELECT LOCATIONID INTO v_loc_id FROM (SELECT LOCATIONID FROM BOOK_LOCATION WHERE BRANCHID = v_branch_id ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1;
            
            INSERT INTO BOOK_COPY (BOOKID, BRANCHID, LOCATIONID, STATUS) 
            VALUES (v_book_id, v_branch_id, v_loc_id, 'Available');
        EXCEPTION WHEN OTHERS THEN NULL;
        END;
    END LOOP;
    
    FOR i IN 1..100 LOOP
        BEGIN
            SELECT COPYID INTO v_copy_id FROM (SELECT COPYID FROM BOOK_COPY WHERE STATUS = 'Available' ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1;
            SELECT MEMBERID INTO v_member_id FROM (SELECT MEMBERID FROM MEMBER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1;
            SELECT LIBRARIANID INTO v_lib_id FROM (SELECT LIBRARIANID FROM LIBRARIAN ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1;
            
            INSERT INTO LOAN (COPYID, MEMBERID, LIBRARIANID, ISSUEDATE, DUEDATE, RETURNDATE, STATUS)
            VALUES (v_copy_id, v_member_id, v_lib_id, SYSDATE - 20, SYSDATE - 6, NULL, 'Active');
        EXCEPTION WHEN OTHERS THEN NULL;
        END;
    END LOOP;
    
    FOR i IN 1..20 LOOP
        BEGIN
            SELECT LOANID INTO v_loan_id FROM (SELECT LOANID FROM LOAN ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1;
            SELECT MEMBERID INTO v_member_id FROM (SELECT MEMBERID FROM LOAN WHERE LOANID = v_loan_id);
            INSERT INTO FINE (LOANID, MEMBERID, FINEAMOUNT, FINEDATE, FINESTATUS)
            VALUES (v_loan_id, v_member_id, 25, SYSDATE, 'Unpaid');
        EXCEPTION WHEN OTHERS THEN NULL;
        END;
    END LOOP;
    
    COMMIT;
END;
/
EXIT;
