-- ============================================================
-- FULL DATABASE INTEGRITY CHECK
-- ============================================================
SET LINESIZE 200;
SET PAGESIZE 0;

PROMPT === DUPLICATE PK CHECK ===
SELECT 'DUPLICATE BOOKID' ERR, COUNT(*) CNT FROM BOOK GROUP BY BOOKID HAVING COUNT(*) > 1;
SELECT 'DUPLICATE MEMBERID' ERR, COUNT(*) CNT FROM MEMBER GROUP BY MEMBERID HAVING COUNT(*) > 1;
SELECT 'DUPLICATE LOANID' ERR, COUNT(*) CNT FROM LOAN GROUP BY LOANID HAVING COUNT(*) > 1;
SELECT 'DUPLICATE AUTHORID' ERR, COUNT(*) CNT FROM AUTHOR GROUP BY AUTHORID HAVING COUNT(*) > 1;
SELECT 'DUPLICATE FINEID' ERR, COUNT(*) CNT FROM FINE GROUP BY FINEID HAVING COUNT(*) > 1;

PROMPT === ORPHAN FK CHECK ===
SELECT 'BOOK orphan CATEGORYID' ERR, COUNT(*) CNT FROM BOOK WHERE CATEGORYID NOT IN (SELECT CATEGORYID FROM CATEGORY);
SELECT 'BOOK orphan PUBLISHERID' ERR, COUNT(*) CNT FROM BOOK WHERE PUBLISHERID NOT IN (SELECT PUBLISHERID FROM PUBLISHER);
SELECT 'BOOK_COPY orphan BOOKID' ERR, COUNT(*) CNT FROM BOOK_COPY WHERE BOOKID NOT IN (SELECT BOOKID FROM BOOK);
SELECT 'BOOK_COPY orphan BRANCHID' ERR, COUNT(*) CNT FROM BOOK_COPY WHERE BRANCHID IS NOT NULL AND BRANCHID NOT IN (SELECT BRANCHID FROM LIBRARY_BRANCH);
SELECT 'LOAN orphan COPYID' ERR, COUNT(*) CNT FROM LOAN WHERE COPYID NOT IN (SELECT COPYID FROM BOOK_COPY);
SELECT 'LOAN orphan MEMBERID' ERR, COUNT(*) CNT FROM LOAN WHERE MEMBERID NOT IN (SELECT MEMBERID FROM MEMBER);
SELECT 'FINE orphan LOANID' ERR, COUNT(*) CNT FROM FINE WHERE LOANID IS NOT NULL AND LOANID NOT IN (SELECT LOANID FROM LOAN);
SELECT 'PAYMENT orphan FINEID' ERR, COUNT(*) CNT FROM PAYMENT WHERE FINEID IS NOT NULL AND FINEID NOT IN (SELECT FINEID FROM FINE);
SELECT 'WRITTEN_BY orphan BOOKID' ERR, COUNT(*) CNT FROM WRITTEN_BY WHERE BOOKID NOT IN (SELECT BOOKID FROM BOOK);
SELECT 'WRITTEN_BY orphan AUTHORID' ERR, COUNT(*) CNT FROM WRITTEN_BY WHERE AUTHORID NOT IN (SELECT AUTHORID FROM AUTHOR);
SELECT 'RESERVATION orphan MEMBERID' ERR, COUNT(*) CNT FROM RESERVATION WHERE MEMBERID NOT IN (SELECT MEMBERID FROM MEMBER);
SELECT 'RESERVATION orphan BOOKID' ERR, COUNT(*) CNT FROM RESERVATION WHERE BOOKID NOT IN (SELECT BOOKID FROM BOOK);

PROMPT === INVALID CHECK CONSTRAINT VALUES ===
SELECT 'LOAN invalid STATUS' ERR, STATUS, COUNT(*) CNT FROM LOAN WHERE STATUS NOT IN ('Active','Returned','Overdue') GROUP BY STATUS;
SELECT 'BOOK_COPY invalid STATUS' ERR, STATUS, COUNT(*) CNT FROM BOOK_COPY WHERE STATUS NOT IN ('Available','Issued','Lost','Damaged') GROUP BY STATUS;
SELECT 'FINE invalid FINESTATUS' ERR, FINESTATUS, COUNT(*) CNT FROM FINE WHERE FINESTATUS NOT IN ('Paid','Unpaid') GROUP BY FINESTATUS;
SELECT 'RESERVATION invalid STATUS' ERR, STATUS, COUNT(*) CNT FROM RESERVATION WHERE STATUS NOT IN ('Pending','Fulfilled','Cancelled') GROUP BY STATUS;
SELECT 'MEMBER invalid MEMBERTYPE' ERR, MEMBERTYPE, COUNT(*) CNT FROM MEMBER WHERE MEMBERTYPE NOT IN ('Regular','Premium','Student') GROUP BY MEMBERTYPE;

PROMPT === TRIGGER VERIFICATION: COPY STATUS AFTER LOANS ===
SELECT 'Issued copies with no Active loan' ISSUE, COUNT(*) CNT
FROM BOOK_COPY bc
WHERE bc.STATUS = 'Issued'
AND NOT EXISTS (SELECT 1 FROM LOAN l WHERE l.COPYID = bc.COPYID AND l.STATUS = 'Active');

PROMPT === DASHBOARD NUMBERS (matches API) ===
SELECT 'totalBooks' K, COUNT(*) V FROM BOOK;
SELECT 'totalBookCopies' K, COUNT(*) V FROM BOOK_COPY;
SELECT 'availableCopies' K, COUNT(*) V FROM BOOK_COPY WHERE STATUS = 'Available';
SELECT 'issuedCopies' K, COUNT(*) V FROM BOOK_COPY WHERE STATUS = 'Issued';
SELECT 'totalMembers' K, COUNT(*) V FROM MEMBER;
SELECT 'activeLoans' K, COUNT(*) V FROM LOAN WHERE STATUS = 'Active';
SELECT 'overdueLoans' K, COUNT(*) V FROM LOAN WHERE STATUS = 'Overdue';
SELECT 'activeReservations' K, COUNT(*) V FROM RESERVATION WHERE STATUS = 'Pending';
SELECT 'outstandingFines' K, COUNT(*) V FROM FINE WHERE FINESTATUS = 'Unpaid';
SELECT 'totalAuthors' K, COUNT(*) V FROM AUTHOR;
SELECT 'totalPublishers' K, COUNT(*) V FROM PUBLISHER;
SELECT 'totalBranches' K, COUNT(*) V FROM LIBRARY_BRANCH;

EXIT;
