-- Drop tables if they exist to allow clean recreation
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE PAYMENT CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE FINE CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE RESERVATION CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE LOAN CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE WRITTEN_BY CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE BOOK_COPY CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE BOOK CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE LIBRARIAN CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE BOOK_LOCATION CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE LIBRARY_BRANCH CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE MEMBER CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE AUTHOR CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE PUBLISHER CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE CATEGORY CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE SUPPLIER CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- Independent Tables
CREATE TABLE CATEGORY (
    CategoryID NUMBER PRIMARY KEY,
    CategoryName VARCHAR2(100) NOT NULL,
    Description VARCHAR2(255)
);

CREATE TABLE PUBLISHER (
    PublisherID NUMBER PRIMARY KEY,
    PublisherName VARCHAR2(100) NOT NULL,
    Address VARCHAR2(255),
    Phone VARCHAR2(20),
    Email VARCHAR2(100)
);

CREATE TABLE AUTHOR (
    AuthorID NUMBER PRIMARY KEY,
    AuthorName VARCHAR2(100) NOT NULL,
    Nationality VARCHAR2(50),
    Biography VARCHAR2(1000)
);

CREATE TABLE MEMBER (
    MemberID NUMBER PRIMARY KEY,
    MemberName VARCHAR2(100) NOT NULL,
    Address VARCHAR2(255),
    Phone VARCHAR2(20),
    Email VARCHAR2(100) UNIQUE,
    MemberType VARCHAR2(50),
    DateJoined DATE DEFAULT SYSDATE
);

CREATE TABLE LIBRARY_BRANCH (
    BranchID NUMBER PRIMARY KEY,
    BranchName VARCHAR2(100) NOT NULL,
    Address VARCHAR2(255),
    Phone VARCHAR2(20)
);

CREATE TABLE SUPPLIER (
    SupplierID NUMBER PRIMARY KEY,
    SupplierName VARCHAR2(100) NOT NULL,
    Phone VARCHAR2(20),
    Email VARCHAR2(100)
);

-- Dependent Tables
CREATE TABLE BOOK_LOCATION (
    LocationID NUMBER PRIMARY KEY,
    LocationName VARCHAR2(50) NOT NULL,
    Description VARCHAR2(255),
    BranchID NUMBER,
    CONSTRAINT fk_book_loc_branch FOREIGN KEY (BranchID) REFERENCES LIBRARY_BRANCH(BranchID)
);

CREATE TABLE LIBRARIAN (
    LibrarianID NUMBER PRIMARY KEY,
    LibrarianName VARCHAR2(100) NOT NULL,
    Phone VARCHAR2(20),
    Email VARCHAR2(100) UNIQUE,
    BranchID NUMBER,
    CONSTRAINT fk_librarian_branch FOREIGN KEY (BranchID) REFERENCES LIBRARY_BRANCH(BranchID)
);

CREATE TABLE BOOK (
    BookID NUMBER PRIMARY KEY,
    ISBN VARCHAR2(20) UNIQUE,
    Title VARCHAR2(255) NOT NULL,
    CategoryID NUMBER,
    PublisherID NUMBER,
    Price NUMBER(10,2),
    Edition VARCHAR2(50),
    PublishYear NUMBER(4),
    CONSTRAINT fk_book_category FOREIGN KEY (CategoryID) REFERENCES CATEGORY(CategoryID),
    CONSTRAINT fk_book_publisher FOREIGN KEY (PublisherID) REFERENCES PUBLISHER(PublisherID)
);

CREATE TABLE WRITTEN_BY (
    BookID NUMBER,
    AuthorID NUMBER,
    PRIMARY KEY (BookID, AuthorID),
    CONSTRAINT fk_writtenby_book FOREIGN KEY (BookID) REFERENCES BOOK(BookID),
    CONSTRAINT fk_writtenby_author FOREIGN KEY (AuthorID) REFERENCES AUTHOR(AuthorID)
);

CREATE TABLE BOOK_COPY (
    CopyID NUMBER PRIMARY KEY,
    BookID NUMBER,
    BranchID NUMBER,
    LocationID NUMBER,
    AccessionNo VARCHAR2(50) UNIQUE,
    Status VARCHAR2(50) CHECK (Status IN ('Available', 'Issued', 'Lost', 'Damaged')),
    ShelfLocation VARCHAR2(50),
    DateAcquired DATE DEFAULT SYSDATE,
    CONSTRAINT fk_copy_book FOREIGN KEY (BookID) REFERENCES BOOK(BookID),
    CONSTRAINT fk_copy_branch FOREIGN KEY (BranchID) REFERENCES LIBRARY_BRANCH(BranchID),
    CONSTRAINT fk_copy_location FOREIGN KEY (LocationID) REFERENCES BOOK_LOCATION(LocationID)
);

CREATE TABLE LOAN (
    LoanID NUMBER PRIMARY KEY,
    MemberID NUMBER,
    CopyID NUMBER,
    LibrarianID NUMBER,
    IssueDate DATE DEFAULT SYSDATE,
    DueDate DATE,
    ReturnDate DATE,
    Status VARCHAR2(50) CHECK (Status IN ('Active', 'Returned', 'Overdue')),
    CONSTRAINT fk_loan_member FOREIGN KEY (MemberID) REFERENCES MEMBER(MemberID),
    CONSTRAINT fk_loan_copy FOREIGN KEY (CopyID) REFERENCES BOOK_COPY(CopyID),
    CONSTRAINT fk_loan_librarian FOREIGN KEY (LibrarianID) REFERENCES LIBRARIAN(LibrarianID)
);

CREATE TABLE RESERVATION (
    ReservationID NUMBER PRIMARY KEY,
    MemberID NUMBER,
    BookID NUMBER,
    ReservationDate DATE DEFAULT SYSDATE,
    Status VARCHAR2(50) CHECK (Status IN ('Pending', 'Fulfilled', 'Cancelled')),
    CONSTRAINT fk_res_member FOREIGN KEY (MemberID) REFERENCES MEMBER(MemberID),
    CONSTRAINT fk_res_book FOREIGN KEY (BookID) REFERENCES BOOK(BookID)
);

CREATE TABLE FINE (
    FineID NUMBER PRIMARY KEY,
    LoanID NUMBER,
    MemberID NUMBER,
    FineAmount NUMBER(10,2),
    FineDate DATE DEFAULT SYSDATE,
    FineStatus VARCHAR2(50) CHECK (FineStatus IN ('Unpaid', 'Paid')),
    CONSTRAINT fk_fine_loan FOREIGN KEY (LoanID) REFERENCES LOAN(LoanID),
    CONSTRAINT fk_fine_member FOREIGN KEY (MemberID) REFERENCES MEMBER(MemberID)
);

CREATE TABLE PAYMENT (
    PaymentID NUMBER PRIMARY KEY,
    FineID NUMBER,
    MemberID NUMBER,
    Amount NUMBER(10,2),
    PaymentDate DATE DEFAULT SYSDATE,
    PaymentMode VARCHAR2(50),
    CONSTRAINT fk_payment_fine FOREIGN KEY (FineID) REFERENCES FINE(FineID),
    CONSTRAINT fk_payment_member FOREIGN KEY (MemberID) REFERENCES MEMBER(MemberID)
);
