-- Master Data Insertion Script
SET SERVEROUTPUT ON;
PROMPT Inserting data into AUTHOR...
@../data/authors.sql

PROMPT Inserting data into PUBLISHER...
@../data/publishers.sql

PROMPT Inserting data into CATEGORY...
@../data/categories.sql

PROMPT Inserting data into LIBRARY_BRANCH...
@../data/library_branches.sql

PROMPT Inserting data into SUPPLIER...
@../data/suppliers.sql

PROMPT Inserting data into BOOK...
@../data/books.sql

PROMPT Inserting data into BOOK_LOCATION...
@../data/book_locations.sql

PROMPT Inserting data into BOOK_COPY...
@../data/book_copies.sql

PROMPT Inserting data into LIBRARIAN...
@../data/librarians.sql

PROMPT Inserting data into MEMBER...
@../data/members.sql

PROMPT Inserting data into WRITTEN_BY...
@../data/written_by.sql

PROMPT Inserting data into LOAN...
@../data/loans.sql

PROMPT Inserting data into RESERVATION...
@../data/reservations.sql

PROMPT Inserting data into FINE...
@../data/fines.sql

PROMPT Inserting data into PAYMENT...
@../data/payments.sql

PROMPT Data insertion complete.
